/** Portal teams & workspaces — FR / EN (specs 37–38). */

export const teamsFr = {
  navLabel: "Équipes",
  workspaceLabel: "Espace de travail",
  personal: "Personnel",
  ownerBadge: "Propriétaire",
  switchWorkspace: "Changer d’espace",
  openTeams: "Ouvrir les équipes",
  listTitle: "Équipes & espaces de travail",
  backToTeamsList: "Retour aux équipes",
  listDescription: "Espaces partagés : membres, invitations et clés d’API d’équipe.",
  createTeam: "Créer une équipe",
  open: "Ouvrir",
  seats: "{{used}} / {{max}} sièges",
  seatsUnknownMax: "{{used}} / — sièges",
  teamCardSeatsCaption: "Membres acceptés et invitations en attente comptés dans l’occupation.",
  teamCardSeatsCaptionLegacy: "sièges occupés (plafond équipe)",
  teamCardSeatsCaptionNoMax: "sièges actifs — plafond non affiché",
  teamCardSeatsShortLabel: "Sièges",
  teamCardSeatsTooltip: "Sièges : utilisés / plafond (membres + invitations en attente).",
  roleOwner: "Propriétaire",
  roleAdmin: "Admin",
  roleCollaborator: "Collaborateur",
  youAre: "Vous : {{role}}",
  upgradeTitle: "Création d’équipes indisponible sur votre plan",
  upgradeBody:
    "Les équipes sont réservées aux plans Pro et Plus. Vous pouvez toujours être invité dans une équipe existante.",
  upgradeCta: "Voir l’abonnement",
  limitReached: "Limite d’équipes atteinte pour votre plan.",
  featureUnavailable: "Fonction équipes indisponible.",
  createTitle: "Créer une équipe",
  createDescription: "Nommez l’équipe et invitez au moins une personne (e-mail + rôle).",
  teamName: "Nom de l’équipe",
  invitesSection: "Invitations initiales",
  email: "E-mail",
  role: "Rôle",
  addInviteRow: "Ajouter une invitation",
  removeRow: "Retirer",
  submitCreate: "Créer l’équipe",
  creating: "Création…",
  minInvites: "Ajoutez au moins une invitation valide.",
  detailTitle: "Équipe",
  tabOverview: "Vue d’ensemble",
  tabMembers: "Membres",
  tabInvitations: "Invitations",
  tabInstances: "Instances",
  tabApiKeys: "Clés API équipe",
  tabDanger: "Zone de danger",
  rename: "Enregistrer le nom",
  saving: "Enregistrement…",
  deleteTeam: "Supprimer l’équipe",
  dangerOwnerOnly: "Seul le propriétaire peut supprimer l’équipe.",
  dangerNoAccess: "Cette action est réservée au propriétaire.",
  deleteConfirm: "Tapez le nom de l’équipe pour confirmer",
  leaveTeam: "Quitter l’équipe",
  removeMember: "Retirer",
  resendInvite: "Renvoyer",
  revokeInvite: "Révoquer",
  inviteEmail: "E-mail à inviter",
  sendInvite: "Envoyer l’invitation",
  inviteSent: "Invitation envoyée.",
  inviteNoSeatsHint:
    "Tous les sièges sont utilisés (membres + invitations). Retirez un membre ou une invitation, ou faites évoluer le plan du propriétaire.",
  inviteStatusColumn: "Statut",
  inviteStatusPending: "En attente",
  inviteActionsColumn: "Actions",
  expiresIn: "Expire dans {{relative}}",
  expired: "Expiré",
  instanceAssignTitle: "Assigner une instance",
  instanceId: "ID instance",
  memberUserId: "ID utilisateur membre",
  memberSelectLabel: "Membre",
  memberSelectPlaceholder: "Choisir un membre…",
  instanceSelectPlaceholder: "Choisir une instance…",
  instanceAssignNoMembers: "Aucun membre n’est disponible pour l’assignation (ou seul le propriétaire est listé).",
  instanceAccessGridIntro:
    "Accès par instance : cochez les cases pour autoriser chaque collaborateur sur une instance WhatsApp (propriétaires et admins ont déjà accès à toutes les instances).",
  instanceAccessNoCollaborators:
    "Aucun collaborateur dans cette équipe. Invitez des membres en rôle « Collaborateur » pour restreindre l’accès par instance.",
  instanceAccessNoInstances: "Aucune instance dans cet espace équipe. Créez ou connectez une instance en contexte équipe.",
  instanceAccessCollaboratorColumn: "Collaborateur",
  instanceAccessToggleAria: "{{member}} — accès à {{instance}}",
  instanceAccessSaved: "Accès mis à jour",
  collaboratorNoInstanceAssignments: "Aucune instance ne vous est assignée pour le moment.",
  keysEmptyTitle: "Aucune clé d’API d’équipe",
  keysEmptyDescription:
    "Créez une clé pour les scripts et intégrations (préfixe msgf_team_, en-tête x-team-id). Les clés secrètes ne s’affichent qu’une fois.",
  assign: "Assigner",
  unassign: "Retirer l’assignation",
  apiKeyName: "Nom de la clé",
  createApiKey: "Créer une clé",
  cancelAction: "Annuler",
  revokeApiKey: "Révoquer",
  secretOnceTitle: "Clé créée — copiez-la maintenant",
  secretOnceHint: "Cette valeur secrète ne sera plus affichée.",
  copySecret: "Copier",
  copySecretToast: "Copié dans le presse-papiers",
  keysHintTeam: "Les clés d’équipe utilisent le préfixe msgf_team_ et l’en-tête X-Team-Id.",
  collaboratorKeysHidden: "Les clés API d’équipe sont réservées au propriétaire et aux administrateurs.",
  instanceTabCollaboratorHint:
    "En tant que collaborateur, vous ne pouvez pas assigner d’instances ici. Utilisez uniquement les instances qui vous sont assignées dans l’espace équipe.",
  billingHidden: "La facturation du propriétaire n’est pas visible pour ce rôle.",
  cannotRemoveOwner: "Le propriétaire ne peut pas être retiré.",
  ownerCannotLeave: "Le propriétaire doit supprimer l’équipe pour la quitter.",
  inboxTitle: "Invitations en attente",
  inboxDescription: "Invitations reçues sur votre compte.",
  inboxEmpty: "Aucune invitation pour le moment. Les invitations apparaîtront ici lorsqu’une équipe vous invitera.",
  accept: "Accepter",
  declineOptional: "Ignorer (expiration 24h)",
  invitePageTitle: "Accepter une invitation",
  invitePageLoading: "Validation de l’invitation…",
  invitePageSuccess: "Invitation acceptée. Redirection…",
  invitePageError: "Impossible d’accepter l’invitation.",
  noToken: "Lien d’invitation invalide (token manquant).",
  backDashboard: "Retour au tableau de bord",
  loadListError: "Impossible de charger les équipes.",
  loadDetailError: "Impossible de charger l’équipe.",
  loadInvitesError: "Impossible de charger vos invitations.",
  errors: {
    TEAM_FEATURE_UNAVAILABLE: "Fonction équipes indisponible sur votre plan.",
    TEAM_LIMIT_REACHED: "Nombre maximum d’équipes atteint.",
    TEAM_SEAT_LIMIT_REACHED: "Limite de sièges atteinte.",
    TEAM_NOT_FOUND: "Équipe introuvable.",
    TEAM_ACCESS_DENIED: "Accès refusé.",
    INVITE_INVALID_OR_EXPIRED: "Invitation invalide ou expirée.",
    INVITE_EMAIL_MISMATCH: "L’e-mail du compte ne correspond pas à l’invitation.",
    INVITE_DUPLICATE_MEMBER: "Ce membre fait déjà partie de l’équipe.",
    INSTANCE_NOT_ASSIGNED: "Instance non assignée à ce membre.",
    PLAN_CHANGE_BLOCKED_ACTIVE_TEAMS: "Impossible de rétrograder : des équipes actives existent.",
    UNKNOWN: "Une erreur est survenue.",
  },
} as const

export const teamsEn = {
  navLabel: "Teams",
  workspaceLabel: "Workspace",
  personal: "Personal",
  ownerBadge: "Owner",
  switchWorkspace: "Switch workspace",
  openTeams: "Open teams",
  listTitle: "Teams & workspaces",
  backToTeamsList: "Back to teams",
  listDescription: "Shared workspaces: members, invitations, and team API keys.",
  createTeam: "Create team",
  open: "Open",
  seats: "{{used}} / {{max}} seats",
  seatsUnknownMax: "{{used}} / — seats",
  teamCardSeatsCaption: "Accepted members and pending invites both count toward usage.",
  teamCardSeatsCaptionLegacy: "seats in use (team cap)",
  teamCardSeatsCaptionNoMax: "active seats — cap not shown",
  teamCardSeatsShortLabel: "Seats",
  teamCardSeatsTooltip: "Seats: used / cap (members + pending invites).",
  roleOwner: "Owner",
  roleAdmin: "Admin",
  roleCollaborator: "Collaborator",
  youAre: "You: {{role}}",
  upgradeTitle: "Team creation is not available on your plan",
  upgradeBody:
    "Creating teams is available on Pro and Plus. You can still be invited to an existing team on any plan.",
  upgradeCta: "View billing",
  limitReached: "Team limit reached for your plan.",
  featureUnavailable: "Teams feature unavailable.",
  createTitle: "Create a team",
  createDescription: "Name the team and invite at least one person (email + role).",
  teamName: "Team name",
  invitesSection: "Initial invitations",
  email: "Email",
  role: "Role",
  addInviteRow: "Add invitation",
  removeRow: "Remove",
  submitCreate: "Create team",
  creating: "Creating…",
  minInvites: "Add at least one valid invitation.",
  detailTitle: "Team",
  tabOverview: "Overview",
  tabMembers: "Members",
  tabInvitations: "Invitations",
  tabInstances: "Instances",
  tabApiKeys: "Team API keys",
  tabDanger: "Danger zone",
  rename: "Save name",
  saving: "Saving…",
  deleteTeam: "Delete team",
  dangerOwnerOnly: "Only the team owner can delete the team.",
  dangerNoAccess: "This action is limited to the team owner.",
  deleteConfirm: "Type the team name to confirm",
  leaveTeam: "Leave team",
  removeMember: "Remove",
  resendInvite: "Resend",
  revokeInvite: "Revoke",
  inviteEmail: "Email to invite",
  sendInvite: "Send invitation",
  inviteSent: "Invitation sent.",
  inviteNoSeatsHint:
    "All seats are in use (members + pending invites). Remove a member or an invite, or upgrade the owner’s plan.",
  inviteStatusColumn: "Status",
  inviteStatusPending: "Pending",
  inviteActionsColumn: "Actions",
  expiresIn: "Expires in {{relative}}",
  expired: "Expired",
  instanceAssignTitle: "Assign instance",
  instanceId: "Instance ID",
  memberUserId: "Member user ID",
  memberSelectLabel: "Member",
  memberSelectPlaceholder: "Select a member…",
  instanceSelectPlaceholder: "Select an instance…",
  instanceAssignNoMembers: "No members are available to assign, or only the owner is listed.",
  instanceAccessGridIntro:
    "Per-instance access: check the boxes to let each collaborator use a WhatsApp instance (owners and admins already have access to every instance).",
  instanceAccessNoCollaborators:
    "No collaborators on this team yet. Invite members as “Collaborator” to restrict access per instance.",
  instanceAccessNoInstances: "No instances in this team workspace yet. Create or connect an instance while in team context.",
  instanceAccessCollaboratorColumn: "Collaborator",
  instanceAccessToggleAria: "{{member}} — access to {{instance}}",
  instanceAccessSaved: "Access updated",
  collaboratorNoInstanceAssignments: "No instances are assigned to you yet.",
  keysEmptyTitle: "No team API keys yet",
  keysEmptyDescription:
    "Create a key for server integrations (msgf_team_ prefix, x-team-id header). Secrets are shown only once.",
  assign: "Assign",
  unassign: "Unassign",
  apiKeyName: "Key name",
  createApiKey: "Create key",
  cancelAction: "Cancel",
  revokeApiKey: "Revoke",
  secretOnceTitle: "Key created — copy it now",
  secretOnceHint: "This secret will not be shown again.",
  copySecret: "Copy",
  copySecretToast: "Copied to clipboard",
  keysHintTeam: "Team keys use the msgf_team_ prefix and the X-Team-Id header.",
  collaboratorKeysHidden: "Team API keys are available to owners and admins only.",
  instanceTabCollaboratorHint:
    "As a collaborator you cannot assign instances here. Use only instances assigned to you in the team workspace.",
  billingHidden: "Owner billing is not visible for your role.",
  cannotRemoveOwner: "The owner cannot be removed.",
  ownerCannotLeave: "Owners must delete the team instead of leaving.",
  inboxTitle: "Pending invitations",
  inboxDescription: "Invitations sent to your account email.",
  inboxEmpty: "No invitations yet. When a team invites you, it will show up here.",
  accept: "Accept",
  declineOptional: "Ignore (expires in 24h)",
  invitePageTitle: "Accept invitation",
  invitePageLoading: "Validating invitation…",
  invitePageSuccess: "Invitation accepted. Redirecting…",
  invitePageError: "Could not accept the invitation.",
  noToken: "Invalid invite link (missing token).",
  backDashboard: "Back to dashboard",
  loadListError: "Could not load teams.",
  loadDetailError: "Could not load team.",
  loadInvitesError: "Could not load your invitations.",
  errors: {
    TEAM_FEATURE_UNAVAILABLE: "Teams are not available on your plan.",
    TEAM_LIMIT_REACHED: "Maximum number of teams reached.",
    TEAM_SEAT_LIMIT_REACHED: "Seat limit reached.",
    TEAM_NOT_FOUND: "Team not found.",
    TEAM_ACCESS_DENIED: "Access denied.",
    INVITE_INVALID_OR_EXPIRED: "Invitation is invalid or expired.",
    INVITE_EMAIL_MISMATCH: "Your account email does not match the invitation.",
    INVITE_DUPLICATE_MEMBER: "This user is already a member.",
    INSTANCE_NOT_ASSIGNED: "Instance is not assigned to this member.",
    PLAN_CHANGE_BLOCKED_ACTIVE_TEAMS: "Cannot downgrade while active teams exist.",
    UNKNOWN: "Something went wrong.",
  },
} as const
