import type { PortalLocale } from "@/lib/portal-locale"

export const portalCopy = {
  fr: {
    nav: {
      dashboard: "Tableau de bord",
      instances: "Instances",
      messages: "Messages",
      campaigns: "Campagnes",
      contacts: "Contacts",
      templates: "Templates",
      webhooks: "Webhooks",
      numberLookups: "Number Lookups",
      apiKeys: "Clés API",
      billing: "Abonnement",
    },
    topnav: {
      light: "Clair",
      dark: "Sombre",
      profile: "Profil",
      billing: "Facturation",
      logout: "Se déconnecter",
      language: "Langue",
      upgrade: "Mettre à niveau",
    },
    titles: {
      dashboard: "Tableau de bord",
      instances: "Instances",
      messages: "Messages",
      newMessage: "Nouveau message",
      campaigns: "Campagnes",
      newCampaign: "Nouvelle campagne",
      contacts: "Contacts",
      templates: "Templates",
      webhooks: "Webhooks",
      numberLookups: "Number Lookups",
      apiKeys: "Clés API",
      billing: "Abonnement",
      profile: "Profil",
      messagesDetail: "Détail message",
      campaignDetail: "Détail campagne",
      instanceDetail: "Détail instance",
      templateDetail: "Détail template",
      groupDetail: "Détail groupe",
      portal: "Portail",
    },
    common: {
      back: "Retour",
      retry: "Réessayer",
      loading: "Chargement...",
      english: "English",
      french: "Français",
    },
    ui: {
      customVariable: {
        defaultLabel: "Variables custom",
        keyPlaceholder: "code",
        valuePlaceholder: "PROMO10",
        addVariable: "Ajouter une variable",
        removeAria: "Supprimer la variable",
      },
      messageTextarea: {
        defaultPlaceholder: "Rédigez votre message...",
      },
    },
    hooks: {
      campaignsListLoadError: "Impossible de charger les campagnes.",
      campaignNotFound: "Campagne introuvable.",
      contactGroupsLoadError: "Impossible de charger les groupes.",
      contactImportsLoadError: "Impossible de charger les imports.",
      contactImportDone: "Import terminé — {{count}} contacts importés",
      contactImportFailed: "L'import a échoué.",
      contactsLoadError: "Impossible de charger les contacts.",
      globalSearchLoadError: "Impossible de charger la recherche globale.",
      instanceHealthLoadError: "Impossible de charger les données de warmup.",
      instancesLoadError: "Impossible de charger les instances.",
      instanceNotFound: "Instance introuvable.",
      messagesListLoadError: "Impossible de charger les messages.",
      messagesLoadMoreError: "Impossible de charger plus de messages.",
      messageNotFound: "Message introuvable.",
      numberLookupsHistoryLoadError: "Impossible de charger l'historique des lookups.",
      numberLookupInvalidNumbers: "Données invalides. Vérifiez les numéros saisis.",
      numberLookupInstanceNotFound: "Instance introuvable.",
      numberLookupProviderUnavailable:
        "Le service de vérification est temporairement indisponible. Réessayez plus tard.",
      numberLookupExecuteFailed: "Impossible d'exécuter le lookup. Réessayez.",
      numberLookupViewFailed: "Impossible de charger les résultats du lookup.",
      numberLookupNotReady: "Le lookup n'est pas encore terminé.",
      numberLookupGroupNotFound: "Le groupe cible est introuvable.",
      numberLookupImportFailed: "Impossible d'importer les contacts. Réessayez.",
      paymentsLoadError: "Impossible de charger l'historique des paiements.",
      templatesLoadError: "Impossible de charger les modèles.",
      webhooksLoadError: "Impossible de charger les webhooks.",
    },
    auth: {
      layoutMarketing: {
        headlineLine1: "WhatsApp en production,",
        headlineAccent: "sans friction.",
        body: "Connectez vos numéros, automatisez vos messages et pilotez vos campagnes depuis une console conçue pour aller vite.",
        features: [
          {
            title: "Sécurité entreprise",
            description:
              "Chiffrement, webhooks signés et contrôles d'accès pour vos flux critiques.",
          },
          {
            title: "API pensée pour les développeurs",
            description:
              "Une intégration claire, rapide à brancher et stable à opérer en production.",
          },
        ],
      },
      forgotPasswordTitle: "Mot de passe oublié ?",
      forgotPasswordDescription:
        "Saisissez l'adresse e-mail associée à votre compte. Si elle existe, nous vous enverrons un lien de réinitialisation.",
      emailLabel: "Adresse email",
      sendResetLink: "Envoyer le lien de réinitialisation",
      sending: "Envoi...",
      backToLogin: "Retour à la connexion",
      resetSentHeadline:
        "Si un compte existe pour cet e-mail, un lien de réinitialisation a été envoyé.",
      checkInbox: "Vérifiez votre boîte de réception et votre dossier spam.",
      resetExpires: "Le lien de réinitialisation expire dans 60 minutes.",
      invalidEmail: "Veuillez saisir une adresse email valide.",
      forgotPasswordFailed: "Impossible d’envoyer la demande pour le moment. Réessayez.",
      login: {
        loadingTitle: "Connexion en cours",
        loadingDescription: "Nous sécurisons votre session et préparons votre console msgflash.",
        oauthFailed: "Connexion Google échouée. Réessayez.",
        signupSuccess: "Compte créé avec succès. Connectez-vous pour continuer.",
        resetSuccess: "Votre mot de passe a été mis à jour. Vous pouvez maintenant vous connecter.",
        invalidCredentials: "Email ou mot de passe incorrect.",
        emailNotVerified: "Veuillez vérifier votre adresse e-mail avant de vous connecter.",
        validationError: "Vérifiez votre email et mot de passe.",
        loginError: "Erreur de connexion. Réessayez.",
        resendVerificationSuccess:
          "Si votre compte nécessite encore une vérification, un nouveau lien a été envoyé.",
        resendVerificationFailed: "Impossible de renvoyer le lien pour le moment.",
        title: "Bon retour",
        subtitle: "Accédez à votre console de pilotage",
        continueWithGoogle: "Continuer avec Google",
        orEmail: "ou par email",
        emailLabel: "Adresse email",
        passwordLabel: "Mot de passe",
        forgotPassword: "Mot de passe oublié ?",
        resendVerification: "Renvoyer l’e-mail de vérification",
        submit: "Se connecter",
        submitting: "Connexion...",
        noAccount: "Nouveau sur la plateforme ?",
        signupCta: "S'inscrire",
      },
      signup: {
        loadingTitle: "Création du compte",
        loadingDescription: "Nous préparons votre espace msgflash et finalisons votre inscription.",
        conflict: "Un compte avec cet email existe déjà.",
        validationError: "Vérifiez vos informations et réessayez.",
        genericError: "Erreur de connexion. Réessayez.",
        resendVerificationFailed: "Impossible de renvoyer l’e-mail de vérification pour le moment.",
        verifyTitle: "Vérifiez votre e-mail",
        verifyDescriptionPrefix: "Votre compte a bien été créé. Un lien de vérification a été envoyé à",
        verifyStepOpenInbox:
          "Ouvrez votre boîte de réception puis cliquez sur le lien pour activer votre compte.",
        verifyStepSpam:
          "Vérifiez aussi votre dossier spam si vous ne voyez pas l’e-mail immédiatement.",
        resending: "Renvoi en cours...",
        resendVerification: "Renvoyer l’e-mail de vérification",
        backToLogin: "Retour à la connexion",
        openGmail: "Ouvrir Gmail",
        title: "Créer un compte",
        subtitle: "Commencez à expédier vos messages en production.",
        continueWithGoogle: "S'inscrire avec Google",
        orEmail: "ou par email",
        fullName: "Nom complet",
        workEmail: "Email professionnel",
        phone: "Téléphone",
        password: "Mot de passe",
        termsPrefix: "J'accepte les",
        termsLink: "Conditions d'utilisation",
        termsAnd: "et la",
        privacyLink: "Politique de confidentialité",
        submit: "Créer mon compte",
        submitting: "Création...",
        hasAccount: "Déjà un compte ?",
        loginCta: "Se connecter",
        loginHint: "Se connecter →",
        passwordRules: {
          min: "8 caractères minimum",
          upper: "Une majuscule",
          lower: "Une minuscule",
          number: "Un chiffre",
          special: "Un caractère spécial",
        },
      },
      resetPassword: {
        ruleInvalid: "Le mot de passe ne respecte pas les critères requis.",
        mismatch: "Les mots de passe ne correspondent pas.",
        invalidPassword: "Le mot de passe est invalide ou trop court.",
        invalidToken: "Ce lien de réinitialisation est invalide ou a expiré.",
        unauthorized: "Impossible de réinitialiser le mot de passe pour ce compte.",
        genericError: "Impossible de réinitialiser le mot de passe. Réessayez.",
        validatingTitle: "Validation de votre lien de réinitialisation...",
        validatingDescription: "Nous vérifions que votre lien est encore valide.",
        expiredTitle: "Ce lien de réinitialisation est invalide ou a expiré.",
        expiredDescription: "Demandez un nouveau lien pour continuer.",
        requestNew: "Demander un nouveau lien",
        updatingTitle: "Mise à jour du mot de passe",
        updatingDescription: "Nous appliquons votre nouveau mot de passe en toute sécurité.",
        title: "Définir un nouveau mot de passe",
        subtitle: "Choisissez un nouveau mot de passe pour votre compte.",
        successTitle: "Votre mot de passe a été mis à jour avec succès.",
        successDescription: "Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.",
        newPassword: "Nouveau mot de passe",
        confirmPassword: "Confirmer le mot de passe",
        submit: "Réinitialiser le mot de passe",
        submitting: "Mise à jour...",
      },
      verifyEmail: {
        resendSuccess: "Un nouveau lien de vérification a été envoyé.",
        resendFailed: "Impossible de renvoyer le lien pour le moment.",
        loadingTitle: "Vérification de votre e-mail",
        loadingDescription: "Nous validons votre lien et activons votre compte.",
        goToLogin: "Aller à la connexion",
        resend: "Renvoyer l’e-mail de vérification",
        resending: "Renvoi en cours...",
        states: {
          successTitle: "E-mail vérifié",
          successDescription: "Votre compte est maintenant activé. Vous pouvez vous connecter.",
          alreadyVerifiedTitle: "E-mail déjà vérifié",
          alreadyVerifiedDescription:
            "Votre compte est déjà activé. Vous pouvez vous connecter immédiatement.",
          expiredTitle: "Lien expiré",
          expiredDescription:
            "Ce lien de vérification a expiré. Demandez un nouveau lien pour continuer.",
          usedTitle: "Lien déjà utilisé",
          usedDescription:
            "Ce lien a déjà servi. Si votre compte n’est pas activé, demandez un nouveau lien.",
          invalidTitle: "Lien invalide",
          invalidDescription: "Ce lien de vérification n’est pas valide.",
          errorTitle: "Vérification impossible",
          errorDescription: "Nous n’avons pas pu vérifier votre adresse e-mail pour le moment.",
        },
      },
      callback: {
        title: "Connexion à msgflash",
        description: "Nous validons votre identité et ouvrons votre espace en toute sécurité.",
      },
    },
    globalSearch: {
      placeholder: "Recherche globale…",
      shortcut: "⌘K",
      minChars: "Tapez au moins 2 caractères pour lancer la recherche globale.",
      scope: "Recherche dans les pages, instances, messages, campagnes, contacts et groupes.",
      searching: "Recherche en cours…",
      noResults: "Aucun résultat.",
      categories: {
        page: "Page",
        instance: "Instance",
        message: "Message",
        campaign: "Campagne",
        contact: "Contact",
        group: "Groupe",
      },
      staticPages: [
        { id: "page-dashboard", title: "Tableau de bord", description: "Vue d'ensemble du portail", href: "/dashboard" },
        { id: "page-instances", title: "Instances", description: "Gérer les connexions WhatsApp", href: "/instances" },
        { id: "page-messages", title: "Messages", description: "Envoyer et consulter les messages", href: "/messages" },
        { id: "page-campaigns", title: "Campagnes", description: "Piloter les envois en masse", href: "/campaigns" },
        { id: "page-contacts", title: "Contacts", description: "Carnet d'adresses et imports", href: "/contacts" },
        { id: "page-contact-groups", title: "Groupes de contacts", description: "Organiser les contacts par groupes", href: "/contacts/groups" },
        { id: "page-templates", title: "Templates", description: "Bibliothèque de modèles de messages", href: "/templates" },
        { id: "page-webhooks", title: "Webhooks", description: "Recevoir les événements du portal", href: "/webhooks" },
        { id: "page-api-keys", title: "Clés API", description: "Gérer les accès à l'API publique", href: "/api-keys" },
        { id: "page-billing", title: "Abonnement", description: "Abonnement, quotas et paiements", href: "/billing" },
        { id: "page-profile", title: "Profil", description: "Informations personnelles du compte", href: "/profile" },
      ],
      fallbackInstanceDescription: "Instance WhatsApp",
      messagePreview: "Message {{type}}",
      campaignWithStatus: "Campagne {{status}}",
    },
    apiKeys: {
      pageTitle: "Clés API",
      pageDescription: "Gérez vos clés d'accès pour l'API publique.",
      docs: "Documentation API",
      newKey: "Nouvelle clé API",
      quickTitle: "Intégration rapide",
      quickDescription: "Envoyez votre premier message en quelques secondes",
      copy: "Copier",
      copied: "Copié",
      loadError: "Impossible de charger les clés API.",
      emptyTitle: "Aucune clé API pour le moment.",
      emptyDescription: "Créez votre première clé.",
      usageSummary: "Résumé d'utilisation",
      requestsOnPeriod: "requêtes sur",
      thisMonth: "ce mois-ci",
      activeKeys: "Clés actives",
      statusActive: "Active",
      statusRevoked: "Révoquée",
      requests: "requêtes",
      monthlyTrafficShare: "du trafic mensuel",
      none: "Aucune",
      never: "Jamais",
      revoke: "Révoquer",
      tableHeadersLoading: ["Nom", "Préfixe", "Requêtes (mois)", "Dernière utilisation", "Créée le", "Actions"],
      tableHeaders: ["Clé", "Usage ce mois", "Dernière requête", "Dernière utilisation", "Créée le", "Actions"],
      createModal: {
        title: "Nouvelle clé API",
        name: "Nom",
        placeholder: "ex. Application de production",
        cancel: "Annuler",
        create: "Créer",
      },
      createdModal: {
        title: "Clé API créée",
        warning: "C'est la seule fois où cette clé sera affichée. Copiez-la maintenant.",
        confirm: "J'ai copié la clé",
      },
      revokeModal: {
        title: "Révoquer la clé API",
        promptPrefix: "Voulez-vous vraiment révoquer",
        promptSuffix: "Toute application qui utilise cette clé cessera de fonctionner immédiatement.",
        cancel: "Annuler",
      },
      toast: {
        notAvailableOnPlan:
          "Les clés API ne sont pas disponibles sur le plan Gratuit. Changez de plan pour y accéder.",
        maxReached: "Vous avez atteint la limite de clés API. Révoquez une clé existante ou changez de plan.",
        createFailed: "Impossible de créer la clé API.",
        revoked: "Clé API révoquée",
        revokeFailed: "Impossible de révoquer la clé.",
      },
    },
    billing: {
      pageTitle: "Facturation",
      pageDescription: "Gérez votre plan et suivez votre consommation mensuelle.",
      loadErrorTitle: "Impossible de charger les données de facturation",
      planCurrent: "Plan actuel",
      planStatusActive: "Actif",
      planStatusTrial: "Essai",
      planStatusPastDue: "Paiement en retard",
      planStatusCancelled: "Annulé",
      planStatusExpired: "Expiré",
      recurring: "par mois",
      apiRequests: "requêtes API / mois",
      messagesPerMonth: "messages / statuts par mois",
      apiKey: "clé API",
      apiKeys: "clés API",
      webhookEndpoint: "endpoint webhook",
      webhookEndpoints: "endpoints webhook",
      instances: "instances",
      contactGroupsSuffix: "groupes de contacts",
      contactGroupsUnlimited: "Groupes de contacts illimités",
      planActuel: "Plan actuel",
      currentPlan: "Plan actuel",
      availablePlans: "Plans disponibles",
      features: {
        campaigns: "Campagnes",
        statuses: "Statuts WhatsApp",
        webhooks: "Webhooks",
        voiceNotes: "Notes vocales",
      },
      priceUnit: "€ / mois",
      yes: "oui",
      no: "non",
      unlimited: "Illimité",
      percentUsed: "utilisé",
      currentBadge: "Actuel",
      scheduledBadge: "Programmé",
      currentPlanButton: "Plan actuel",
      downgrade: "Rétrograder",
      updatePayment: "Mettre à jour",
      choosePlan: "Choisir un plan",
      cancelScheduledChange: "Annuler ce changement",
      cancelTermination: "Annuler la résiliation",
      cancelChange: "Annuler le changement",
      changePlan: "Changer de plan",
      usageTitle: "Usage",
      messages: "Messages",
      statuses: "Statuts",
      paymentHistory: "Historique des paiements",
      loadingPayments: "Chargement…",
      noPayments: "Aucun paiement enregistré pour le moment",
      paymentTableHeaders: ["Date", "Plan", "Période", "Montant", "Statut"],
      paymentStatusSucceeded: "Réussi",
      paymentStatusFailed: "Échoué",
      paymentStatusRefunded: "Remboursé",
      paymentStatusPending: "En attente",
      pageOf: "Page",
      of: "sur",
      cancelSubscriptionTitle: "Annuler l'abonnement",
      cancelSubscriptionCta: "Annuler l'abonnement",
      cancelSubscriptionKeepAccessPrefix: "Vous conserverez l'accès",
      cancelSubscriptionUntilPrefix: "jusqu'au",
      cancelSubscriptionUntilFallback: "la fin de votre période",
      cancelSubscriptionThenFree: "puis passerez au plan Gratuit.",
      scheduledDowngradeNoticePrefix: "Votre plan passera de",
      scheduledDowngradeNoticeOn: "le",
      scheduledCancelNoticePrefix: "Votre abonnement sera résilié le",
      scheduledCancelNoticeSuffix: "Vous passerez au plan Gratuit.",
      cancelScheduledBadge: "Résiliation programmée",
      downgradeScheduledBadgePrefix: "Rétrogradation →",
      expiresOn: "Expire le",
      renewsOn: "Renouvellement :",
      modals: {
        changePlanTitle: "Changer de plan",
        changePlanDescription: "Choisissez le plan adapté à vos besoins.",
        noPlans: "Impossible de charger les plans. Réessayez.",
        cancelTitle: "Annuler l'abonnement",
        cancelDescription: "Cette action programmera la résiliation à la fin de la période.",
        keepPlan: "Conserver le plan",
        confirmCancel: "Confirmer l'annulation",
        cancelScheduledTitle: "Annuler le changement de plan",
        cancelTerminationTitle: "Annuler la résiliation",
        back: "Retour",
        confirm: "Confirmer",
        scheduledDowngradeUpgradeHintPrefix: "Rétrogradation vers",
        scheduledDowngradeUpgradeHintSuffix:
          "programmée. Un upgrade annulera ce changement automatiquement.",
        scheduledCancelUpgradeHint:
          "Résiliation programmée. Un upgrade annulera la résiliation automatiquement.",
        cancelPeriodTextPrefix: "Votre abonnement sera annulé à la fin de la période en cours",
        cancelPeriodTextSuffix:
          "Vous conserverez l'accès jusqu'à cette date, puis vous serez automatiquement basculé sur le plan gratuit.",
        scheduledCancelKeepPlanPrefix: "Votre abonnement restera actif sur le plan",
        scheduledDowngradeCancelPrefix: "La rétrogradation vers",
        scheduledDowngradeCancelSuffix: "sera annulée. Votre plan",
        scheduledDowngradeCancelSuffix2: "restera actif.",
        currentPlanFallback: "actuel",
        scheduledChangeCancelled: "Ce changement programmé sera annulé.",
      },
      alerts: {
        pastDueTitle: "Paiement en retard",
        pastDueDescription:
          "Votre dernier paiement a échoué. Mettez à jour votre moyen de paiement pour conserver l'accès à votre plan.",
        expiredTitle: "Abonnement expiré",
        expiredDescription: "Votre abonnement a expiré. Choisissez un plan pour continuer à utiliser la plateforme.",
      },
      toast: {
        paymentReceived: "Paiement reçu ! Mise à jour du plan en cours...",
        planUpdated: "Votre plan a été mis à jour.",
        paymentCancelled: "Paiement annulé. Votre plan n'a pas changé.",
        downgradeScheduledPrefix: "Rétrogradation vers",
        downgradeScheduledSuffix: "programmée à la fin de la période.",
        changeAlreadyScheduled: "Un changement de plan est déjà programmé.",
        invalidPlanChange:
          "Ce changement de plan n'est pas possible. Pour passer au plan gratuit, utilisez l'annulation.",
        noActiveSubscription: "Aucun abonnement actif.",
        planUnavailable: "Ce plan n'est pas disponible.",
        paymentTemporarilyUnavailable: "Le paiement est temporairement indisponible. Réessayez plus tard.",
        changeFailed: "Impossible de changer de plan. Réessayez.",
        cancelSuccessPrefix: "Abonnement annulé — accès",
        cancelSuccessSuffix: "conservé jusqu'à la fin de la période.",
        alreadyOnFree: "Vous êtes déjà sur le plan gratuit.",
        cancelFailed: "Impossible d'annuler l'abonnement. Réessayez.",
        scheduledCancelled: "Le changement programmé a été annulé.",
        noScheduledChange: "Aucun changement programmé à annuler.",
        scheduledCancelFailed: "Impossible d'annuler le changement. Réessayez.",
      },
    },
    templates: {
      pageTitle: "Templates",
      pageDescription: "Bibliothèque de modèles réutilisables pour vos messages.",
      newTemplate: "Nouveau template",
      emptyTitle: "Aucun template pour l’instant",
      emptyDescription: "Créez votre premier template texte ou média.",
      editTitle: "Modifier le template",
      deleteTitle: "Supprimer le template",
      deleteConfirm: "Supprimer",
      edit: "Modifier",
      preview: "Aperçu",
      delete: "Supprimer",
      confirmDelete: "Supprimer",
      previous: "Précédent",
      next: "Suivant",
      modifiedAt: "Modifié le",
      media: "Média",
      bodyOptional: "Corps (optionnel)",
      body: "Corps",
      name: "Nom",
      type: "Type",
      templateUpdated: "Template mis à jour",
      templateDeleted: "Template supprimé",
      templateUpdateFailed: "Impossible d'enregistrer le template.",
      templateDeleteFailed: "Impossible de supprimer le template.",
      invalidTemplate: "Ce template contient des placeholders invalides ou une configuration média incomplète.",
      validationError: "Vérifiez les champs obligatoires du template.",
      new: {
        title: "Nouveau template",
        description: "Créez un message réutilisable avec des variables dynamiques.",
        back: "Retour aux templates",
        variableSyntax: "Syntaxe des variables",
        variableSyntaxDescription:
          "Utilisez {{path.to.value}} pour insérer des variables dynamiques. Elles seront remplacées automatiquement lors de l'envoi.",
        customVariables: "Variables personnalisées",
        customVariablesDescription:
          "Définies par vous lors de l'envoi ou de la campagne. Ex : {{custom.code}}, {{custom.amount}}",
        examplesTitle: "Exemples de templates",
        hide: "Masquer",
        show: "Afficher",
        copied: "Copié",
        copy: "Copier",
        infoTitle: "Informations",
        templateName: "Nom du template",
        mediaUrl: "Media URL",
        bodyTitle: "Corps du message",
        bodyDescription:
          "Rédigez votre message en utilisant les variables {{...}}. Cliquez sur les variables ci-dessus pour les insérer.",
        bodyPlaceholder: "Bonjour {{contact.firstName}}, utilisez {{custom.code}} aujourd'hui.",
        variablesDetected: "Variables détectées",
        autoResolved: "Résolues automatiquement",
        toProvideOnSend: "À fournir lors de l'envoi",
        noVariablesDetected:
          "Aucune variable détectée. Utilisez {{contact.firstName}} par exemple.",
        submitHint: "Remplissez le nom et le corps du message pour créer le template.",
        cancel: "Annuler",
        create: "Créer le template",
        created: "Template créé",
        saveFailed: "Impossible d'enregistrer le template.",
        invalid: "Ce template contient des placeholders invalides ou une configuration média incomplète.",
        requiredFields: "Vérifiez les champs obligatoires du template.",
        autoVariables: {
          contact: "Données du contact",
          user: "Vos données utilisateur",
          instance: "Données de l'instance",
        },
        examples: {
          followup: "Relance personnalisée",
          order: "Confirmation de commande",
          notice: "Note de service",
        },
      },
    },
    contacts: {
      pageTitle: "Contacts",
      pageDescription: "Carnet d'adresses, imports CSV et groupes de contacts.",
      newContact: "Nouveau contact",
      addContact: "Ajouter un contact",
      editContact: "Modifier le contact",
      deleteContact: "Supprimer le contact",
      saveContact: "Enregistrer",
      emptyTitle: "Aucun contact pour l’instant",
      emptyDescription: "Ajoutez votre premier contact ou importez un CSV.",
      importContacts: "Importer des contacts CSV",
      importStepUpload: "Choisir le fichier",
      importStepPreview: "Aperçu",
      importStepResult: "Résultat",
      contactAdded: "Contact ajouté",
      contactUpdated: "Contact mis à jour",
      contactDeleted: "Contact supprimé",
      importSuccess: "Contacts importés avec succès",
      importPartial: "Import partiel: certains contacts ont été ignorés.",
      importFailed: "Impossible d'importer le fichier.",
      sampleFile: "Télécharger un exemple CSV",
      fileTooLarge: "Le fichier dépasse 5MB.",
      csvInvalid: "Fichier CSV invalide. Vérifiez les en-têtes et l'encodage.",
      csvTooLarge: "Fichier trop grand. Max 5MB et 10 000 lignes.",
      conflict: "Un contact avec ce numéro existe déjà.",
      phone: "Téléphone",
      tags: "Tags (optionnel)",
      tagsHint: "Séparés par des virgules",
      importContactsButton: "Importer",
      importBack: "Retour",
      importChooseFile: "Choisir le fichier",
      importPreview: "Aperçu",
      importResult: "Résultat",
      importCancelled: "Import annulé",
      contactTablePhone: "Téléphone",
      contactTableName: "Nom",
      contactTableTags: "Tags",
      contactTableGroups: "Groupes",
      contactTableCreatedAt: "Créé le",
      noContactFound: "Aucun contact trouvé.",
      groups: {
        pageTitle: "Groupes de contacts",
        back: "Retour",
        newGroup: "Nouveau groupe",
        emptyTitle: "Aucun groupe pour l'instant.",
        emptyDescription: "Créez votre premier groupe pour organiser vos contacts.",
        created: "Groupe créé",
        updated: "Groupe mis à jour",
        deleted: "Groupe supprimé",
        notFound: "Groupe introuvable.",
        saveFailed: "Impossible d'enregistrer le groupe.",
        updateFailed: "Impossible de mettre à jour le groupe.",
        deleteFailed: "Impossible de supprimer le groupe.",
        maxReached: "Limite de groupes atteinte. Mettez à niveau votre plan.",
        nameConflictPrefix: "Un groupe nommé",
        view: "Voir",
        edit: "Modifier",
        delete: "Supprimer",
        remove: "Retirer",
        save: "Enregistrer",
        cancel: "Annuler",
        loadMore: "Charger plus",
        export: "Exporter",
        exporting: "Export en cours…",
        exportFailed: "Impossible d'exporter le groupe.",
        addContacts: "Ajouter des contacts",
        removeMemberFailed: "Impossible de retirer le contact.",
        removeMemberSuccess: "Contact retiré du groupe",
        addMembersFailed: "Impossible d'ajouter les contacts.",
        addMembersTitle: "Ajouter des contacts au groupe",
        searchMembersPlaceholder: "Rechercher dans les membres...",
        searchContactsPlaceholder: "Rechercher par nom ou numéro...",
        loading: "Chargement…",
        noContactsAvailable: "Aucun contact disponible.",
        noMembers: "Aucun contact dans ce groupe.",
        noMembersDescription: "Ajoutez des contacts pour commencer.",
        createModalTitle: "Nouveau groupe",
        editModalTitle: "Modifier le groupe",
        deleteModalTitle: "Supprimer le groupe",
        removeModalTitle: "Retirer du groupe",
        name: "Nom",
        description: "Description (optionnel)",
        descriptionPlaceholder: "Description du groupe...",
        color: "Couleur",
        customColorTitle: "Couleur personnalisée",
        detailsCountSuffix: "contact",
        detailsCountSuffixPlural: "contacts",
        createdAt: "Ajouté le",
        table: {
          name: "Nom",
          phone: "Téléphone",
          tags: "Tags",
          addedAt: "Ajouté le",
        },
      },
    },
    numberLookups: {
      pageTitle: "Number Lookups",
      pageDescription: "Vérifiez la validité d’un numéro puis importez les contacts reconnus.",
      importContacts: "Importer dans un groupe",
      contactsImported: "Contacts importés avec succès",
      partialImport: "Certains contacts ont été importés, d'autres ont été ignorés.",
      lookupStarted: "Lookup lancé. Les résultats seront disponibles sous peu.",
      lookupCompleted: "Lookup terminé",
      lookupFailed: "Lookup échoué. Réessayez.",
      processing: "Lookup en cours de traitement… Les résultats seront disponibles dans quelques instants.",
      history: "Historique",
      emDash: "—",
      detail: {
        title: "Détails du lookup",
        instance: "Instance",
        instanceStatus: "Statut instance",
        requested: "Demandés",
        onWhatsApp: "WhatsApp",
        absent: "Absents",
        invalid: "Invalides",
        invalidNumbers: "Numéros invalides",
        notOnWhatsApp: "Absents de WhatsApp",
        onWhatsAppTitle: "Présents sur WhatsApp",
        normalized: "Normalisé :",
        progress: "Progression",
        completedOn: "Terminé le {{date}}",
        importOne: "Importer {{count}} contact",
        importMany: "Importer {{count}} contacts",
        alreadyImported: "Contacts déjà importés",
        close: "Fermer",
        status: {
          done: "Terminé",
          failed: "Échoué",
          pending: "En attente",
          processing: "En cours",
        },
      },
      historyTable: {
        empty: "Aucun lookup effectué pour le moment.",
        headers: ["Date", "Instance", "Statut", "Demandés", "WhatsApp", "Absents", "Invalides", "Actions"],
        viewDetails: "Voir les détails",
        importContacts: "Importer les contacts",
        imported: "Importé",
        mobileWhatsApp: "WhatsApp:",
        mobileAbsent: "Absents:",
        mobileInvalid: "Invalides:",
      },
      resultsTabs: {
        onWhatsApp: "Sur WhatsApp",
        notOnWhatsApp: "Absents",
        invalid: "Invalides",
        emptyCategory: "Aucun résultat dans cette catégorie.",
        normalized: "Normalisé :",
        reasonPrefix: "Motif :",
      },
    },
    dashboard: {
      pageTitle: "Tableau de bord",
      pageDescription: "Vue d'ensemble de votre activité WhatsApp",
      noInstance: "Aucune instance WhatsApp connectée.",
      connectNow: "Connecter maintenant →",
      messagesThisMonth: "Messages ce mois",
      activeInstances: "Instances actives",
      apiRequestsThisMonth: "Requêtes API ce mois",
      campaignsRunning: "Campagnes en cours",
      active: "Actif",
      noSends: "Aucun envoi",
      online: "En ligne",
      offline: "Hors ligne",
      thisMonth: "Ce mois",
      total: "total",
      usagePlan: "Utilisation — Plan",
      quotaExhausted: "Quota épuisé",
      quotaNear: "Quota presque épuisé",
      messagesStatuses: "Messages & Statuts",
      apiRequests: "Requêtes API",
      quotaResetOn: "Quota réinitialisé le",
      recentMessages: "Messages récents",
      recentCampaigns: "Campagnes récentes",
      seeAll: "Tout voir →",
      noMessages: "Aucun message envoyé.",
      sendFirstMessage: "Envoyer le premier message",
      noCampaigns: "Aucune campagne pour l'instant.",
      createCampaign: "Créer une campagne",
      quickActions: "Actions rapides",
      sendMessage: "Envoyer un message",
      newCampaign: "Nouvelle campagne",
      connectWhatsapp: "Connecter WhatsApp",
      generateApiKey: "Générer une clé API",
      status: {
        queued: "En file",
        sent: "Envoyé",
        delivered: "Livré",
        read: "Lu",
        failed: "Échoué",
        draft: "Brouillon",
        scheduled: "Planifié",
        running: "En cours",
        paused: "En pause",
        pausedQuota: "En pause (quota)",
        pausedPlan: "En pause (plan)",
        completed: "Terminé",
      },
    },
    messages: {
      title: "Nouveau message",
      description: "Envoyez immédiatement ou programmez un message avec suivi d’upload et statut d’action.",
      sendBack: "Retour aux messages",
      draft: "Rédaction libre",
      template: "Utiliser un template",
      instance: "Instance",
      selectInstance: "Sélectionner une instance...",
      noInstance: "Aucune instance connectée disponible.",
      selectTemplate: "Sélectionner un template...",
      variables: "Variables du template",
      uploadSuccess: "Fichier uploadé avec succès.",
      uploadQueued: "Média prêt. Vous pouvez relire puis envoyer.",
      uploadInProgress: "Upload du média en cours...",
      mediaRemoved: "Média supprimé. Vous pouvez en choisir un autre.",
      typeUpdated: "Type de message mis à jour.",
      queuedSuccess: "Message mis en file avec succès.",
      scheduledSuccess: "Message programmé avec succès.",
      sending: "Envoi du message...",
      scheduling: "Programmation du message...",
      queuedNote: "Le message a été mis en file d’envoi.",
      templatePreview: "Aperçu du template actualisé.",
      templatePreviewLoading: "Génération de l’aperçu du template...",
      templatePreviewError: "Impossible de générer l’aperçu du template.",
      recipient: {
        title: "Destinataire",
        manual: "Nouveau numéro",
        contact: "Contact enregistré",
        chooseContact: "Choisir un contact",
        selectContact: "Sélectionner un contact...",
        phoneLabel: "Destinataire (numéro)",
        noContact:
          "Aucun contact enregistré disponible. Ajoutez un contact ou utilisez un nouveau numéro.",
      },
      voiceRecorder: {
        title: "Note vocale",
        description: "Enregistrez votre voix, réécoutez-la puis uploadez-la avant l’envoi final.",
        browserUnsupported: "L’enregistrement vocal n’est pas supporté sur ce navigateur.",
        mimeUnsupported:
          "Votre navigateur ne prend pas en charge un format audio compatible pour les notes vocales. Utilisez plutôt l’envoi de fichier audio.",
        micDisconnected: "Connexion au micro perdue. Enregistrement annulé.",
        silenceDetected: "Nous n’entendons rien. Vérifiez le volume de votre micro.",
        micDenied:
          "Accès micro refusé. Veuillez autoriser le micro dans les paramètres de votre navigateur pour enregistrer.",
        micNotFound: "Aucun microphone détecté. Branchez un périphérique pour continuer.",
        micBusy: "Le microphone est déjà utilisé par une autre application.",
        startFailed: "Impossible de démarrer l’enregistrement vocal.",
        startRecording: "Démarrer l’enregistrement",
        micRequestedOnClick: "Le micro ne sera demandé qu’au clic.",
        recording: "Enregistrement en cours...",
        cancel: "Annuler",
        stop: "Stop",
        remove: "Supprimer",
        rerecord: "Réenregistrer",
        uploadVoiceNote: "Uploader la note",
      },
      detail: {
        notFound: "Message introuvable.",
        backToMessages: "Retour aux messages",
        title: "Détails du message",
        back: "Retour",
        template: "Template",
        sendFailed: "Échec d'envoi",
        status: "Statut",
        type: "Type",
        recipient: "Destinataire",
        instance: "Instance",
        providerId: "ID fournisseur",
        content: "Contenu",
        createdAt: "Créé le",
        updatedAt: "Mis à jour le",
        campaign: "Campagne",
        viewCampaign: "Voir la campagne →",
        contact: "Contact",
        templateRender: "Template Render",
        templateId: "Template ID",
        usedVariables: "Used variables",
        missingVariables: "Missing variables",
        renderCode: "Render code",
        none: "Aucune",
        types: {
          text: "Texte",
          image: "Image",
          video: "Vidéo",
          audio: "Audio",
          voice_note: "Message vocal",
          document: "Document",
        },
      },
      mediaUpload: {
        uploading: "Upload en cours...",
        uploadingHint: "Le fichier est envoyé vers l’hébergement temporaire sécurisé.",
        fileDetails: "{{size}} · {{mime}} · expire le {{date}}",
        replace: "Remplacer",
        tempHostNotice: "Le fichier est hébergé temporairement et supprimé automatiquement après expiration.",
        publicLinkNotice: "Le lien généré est public. N’uploadez pas de document sensible.",
        scheduleExpiryWarning: "Si la date prévue dépasse l’expiration, l’envoi peut échouer.",
        chooseFile: "Choisir un fichier",
        acceptedMax: "{{accepted}} · max {{size}}",
        mediaFieldLabel: {
          image: "Image",
          video: "Vidéo",
          document: "Document",
          audio: "Fichier audio",
          voice_note: "Note vocale",
        },
      },
      buttonBuilder: {
        title: "Boutons",
        add: "Ajouter",
        emptyHint: "Aucun bouton configuré. Ajoutez jusqu'à 2 boutons interactifs.",
        buttonN: "Bouton {{n}}",
        typeLabel: "Type de bouton",
        displayText: "Texte affiché",
        displayPlaceholder: "ex. Visiter le site",
        buttonId: "ID du bouton",
        buttonIdHint: "Identifiant unique pour le callback",
        copyCode: "Code à copier",
        copyPlaceholder: "ex. PROMO2024",
        url: "URL",
        phone: "Numéro de téléphone",
        pixCurrency: "Devise",
        pixRecipientName: "Nom du destinataire",
        pixKeyType: "Type de clé Pix",
        pixKeyTypePlaceholder: "Sélectionner...",
        pixKey: "Clé Pix",
        pixKeyPlaceholder: "ex. 123.456.789-00",
        pixCompanyPlaceholder: "Entreprise SARL",
        types: {
          reply: "Réponse",
          copy: "Copier",
          url: "Lien",
          call: "Appel",
          pix: "Pix",
        },
        pixKeyTypes: {
          cpf: "CPF",
          cnpj: "CNPJ",
          email: "Email",
          phone: "Téléphone",
          random: "Aléatoire",
        },
      },
      sendStatus: {
        progressLabel: "Progression",
        title: "Suivi d’envoi",
        mediaUpload: "Upload média",
        actionStatus: "Statut de l’action",
        mediaExpiryNote: "Le média temporaire doit rester valide jusqu’à l’envoi effectif.",
      },
    },
    instances: {
      health: {
        title: "Warmup & Santé",
        loadError: "Impossible de charger les données de warmup.",
        retry: "Réessayer",
        firstConnected: "Première connexion :",
        hourlyCap: "Cap horaire",
        dailyCap: "Cap journalier",
        maxCampaign: "Max campagne",
        maxColdRatio: "Ratio contacts froids max",
        activityTitle: "Activité récente",
        window1h: "1h",
        window24h: "24h",
        sentUnique: "{{sent}} envoyés · {{unique}} destin.",
        replies: "Réponses",
        repliesLine: "{{in24}} (24h) · {{in7}} (7j)",
        recommendations: "Recommandations",
        states: {
          new: "Nouvelle",
          warming: "En warmup",
          stable: "Stable",
          at_risk: "À risque",
          restricted: "Restreinte",
        },
      },
    },
    campaigns: {
      title: "Nouvelle campagne",
      description: "Configurez et planifiez l'envoi groupé à vos contacts.",
      back: "Retour aux campagnes",
      general: "Informations générales",
      recipients: "Destinataires",
      contentTemplate: "Template",
      contentDirect: "Rédaction libre",
      create: "Créer la campagne",
      created: "Campagne créée avec succès.",
      createdWarmup: "Campagne créée avec recommandations de warmup",
      paused: "Campagne mise en pause",
      resumed: "Campagne reprise",
      resumedWarmup: "Campagne reprise avec recommandations de warmup",
      cancelled: "Campagne annulée",
      deleted: "Campagne supprimée",
      planed: "Campagne planifiée",
      safety: {
        title: "Warmup guidance",
        riskPrefix: "Niveau de risque :",
        riskLow: "Faible",
        riskMedium: "Modéré",
        riskHigh: "Élevé",
        scorePrefix: "Score :",
        reasons: "Raisons",
        recommendations: "Recommandations",
        maxCampaignRecipients: "Max destinataires campagne",
        maxColdRatio: "Ratio contacts froids max",
        audienceTitle: "Audience ({{count}} destinataires)",
        warmContacts: "Contacts chauds",
        coldContacts: "Contacts froids",
        unknownContacts: "Inconnus",
      },
    },
    webhooks: {
      newTitle: "Nouveau webhook",
      newDescription: "Ajoutez un endpoint pour recevoir des notifications d'événements en temps réel.",
      back: "Retour aux webhooks",
      endpointTitle: "Endpoint URL",
      endpointDescription: "L'URL qui recevra les notifications POST.",
      endpointLabel: "URL du webhook",
      eventsTitle: "Événements",
      eventsDescription: "Sélectionnez les événements à recevoir.",
      minEvent: "Sélectionnez au moins un événement.",
      hmacNotice: "La clé de signature HMAC-SHA256 sera affichée une seule fois après la création.",
      cancel: "Annuler",
      create: "Créer le webhook",
      createdTitle: "Webhook créé",
      secretWarning: "Copiez cette clé de signature. Elle ne sera plus jamais affichée.",
      secretLabel: "Clé de signature HMAC-SHA256",
      endpointLabelShort: "Endpoint",
      close: "Fermer",
      viewWebhooks: "Voir les webhooks",
      planBlocked:
        "Les webhooks ne sont pas disponibles sur le plan Gratuit. Passez au plan Starter pour y accéder.",
      errors: {
        planUnavailable: "Les webhooks ne sont pas disponibles sur votre plan.",
        limitReached: "Limite d'endpoints webhook atteinte pour votre plan.",
        saveFailed: "Impossible d'enregistrer l'endpoint.",
      },
      events: {
        messageSent: "Message envoyé",
        messageDelivered: "Message livré",
        messageFailed: "Message échoué",
        instanceConnected: "Instance connectée",
      },
    },
    toasts: {
      lookupCompleted: "Lookup terminé",
      lookupFailed: "Lookup échoué. Réessayez.",
      lookupStarted: "Lookup lancé. Les résultats seront disponibles sous peu.",
      contactsImported: "Contacts importés avec succès",
      partialImport: "Certains contacts ont été importés, d'autres ont été ignorés.",
      instanceCreated: "Instance créée",
      instanceConnected: "WhatsApp connecté !",
      instanceDisconnected: "WhatsApp déconnecté",
      profileUpdated: "Profil mis à jour",
    },
  },
  en: {
    nav: {
      dashboard: "Dashboard",
      instances: "Instances",
      messages: "Messages",
      campaigns: "Campaigns",
      contacts: "Contacts",
      templates: "Templates",
      webhooks: "Webhooks",
      numberLookups: "Number Lookups",
      apiKeys: "API Keys",
      billing: "Billing",
    },
    topnav: {
      light: "Light",
      dark: "Dark",
      profile: "Profile",
      billing: "Billing",
      logout: "Log out",
      language: "Language",
      upgrade: "Upgrade",
    },
    titles: {
      dashboard: "Dashboard",
      instances: "Instances",
      messages: "Messages",
      newMessage: "New Message",
      campaigns: "Campaigns",
      newCampaign: "New Campaign",
      contacts: "Contacts",
      templates: "Templates",
      webhooks: "Webhooks",
      numberLookups: "Number Lookups",
      apiKeys: "API Keys",
      billing: "Billing",
      profile: "Profile",
      messagesDetail: "Message Details",
      campaignDetail: "Campaign Details",
      instanceDetail: "Instance Details",
      templateDetail: "Template Details",
      groupDetail: "Group Details",
      portal: "Portal",
    },
    common: {
      back: "Back",
      retry: "Retry",
      loading: "Loading...",
      english: "English",
      french: "French",
    },
    ui: {
      customVariable: {
        defaultLabel: "Custom variables",
        keyPlaceholder: "code",
        valuePlaceholder: "PROMO10",
        addVariable: "Add variable",
        removeAria: "Remove variable",
      },
      messageTextarea: {
        defaultPlaceholder: "Write your message...",
      },
    },
    hooks: {
      campaignsListLoadError: "Unable to load campaigns.",
      campaignNotFound: "Campaign not found.",
      contactGroupsLoadError: "Unable to load groups.",
      contactImportsLoadError: "Unable to load imports.",
      contactImportDone: "Import finished — {{count}} contacts imported",
      contactImportFailed: "Import failed.",
      contactsLoadError: "Unable to load contacts.",
      globalSearchLoadError: "Unable to load global search.",
      instanceHealthLoadError: "Unable to load warmup data.",
      instancesLoadError: "Unable to load instances.",
      instanceNotFound: "Instance not found.",
      messagesListLoadError: "Unable to load messages.",
      messagesLoadMoreError: "Unable to load more messages.",
      messageNotFound: "Message not found.",
      numberLookupsHistoryLoadError: "Unable to load lookup history.",
      numberLookupInvalidNumbers: "Invalid data. Check the numbers entered.",
      numberLookupInstanceNotFound: "Instance not found.",
      numberLookupProviderUnavailable:
        "The verification service is temporarily unavailable. Please try again later.",
      numberLookupExecuteFailed: "Unable to run lookup. Please try again.",
      numberLookupViewFailed: "Unable to load lookup results.",
      numberLookupNotReady: "Lookup is not finished yet.",
      numberLookupGroupNotFound: "Target group not found.",
      numberLookupImportFailed: "Unable to import contacts. Please try again.",
      paymentsLoadError: "Unable to load payment history.",
      templatesLoadError: "Unable to load templates.",
      webhooksLoadError: "Unable to load webhooks.",
    },
    auth: {
      layoutMarketing: {
        headlineLine1: "WhatsApp in production,",
        headlineAccent: "without friction.",
        body: "Connect your numbers, automate your messages, and run campaigns from a console built for speed.",
        features: [
          {
            title: "Enterprise-grade security",
            description:
              "Encryption, signed webhooks, and access controls for your critical flows.",
          },
          {
            title: "A developer-first API",
            description:
              "A clear integration that is quick to wire and stable to run in production.",
          },
        ],
      },
      forgotPasswordTitle: "Forgot password?",
      forgotPasswordDescription:
        "Enter the email linked to your account. If it exists, we will send you a reset link.",
      emailLabel: "Email address",
      sendResetLink: "Send reset link",
      sending: "Sending...",
      backToLogin: "Back to login",
      resetSentHeadline:
        "If an account exists for this email, a reset link has been sent.",
      checkInbox: "Check your inbox and spam folder.",
      resetExpires: "The reset link expires in 60 minutes.",
      invalidEmail: "Please enter a valid email address.",
      forgotPasswordFailed: "Unable to send request for now. Please try again.",
      login: {
        loadingTitle: "Signing in",
        loadingDescription: "We are securing your session and preparing your msgflash console.",
        oauthFailed: "Google sign-in failed. Please try again.",
        signupSuccess: "Account created successfully. Sign in to continue.",
        resetSuccess: "Your password has been updated. You can now sign in.",
        invalidCredentials: "Incorrect email or password.",
        emailNotVerified: "Please verify your email before signing in.",
        validationError: "Check your email and password.",
        loginError: "Sign-in failed. Please try again.",
        resendVerificationSuccess:
          "If your account still requires verification, a new link has been sent.",
        resendVerificationFailed: "Unable to resend the link right now.",
        title: "Welcome back",
        subtitle: "Access your control console",
        continueWithGoogle: "Continue with Google",
        orEmail: "or with email",
        emailLabel: "Email address",
        passwordLabel: "Password",
        forgotPassword: "Forgot password?",
        resendVerification: "Resend verification email",
        submit: "Sign in",
        submitting: "Signing in...",
        noAccount: "New to the platform?",
        signupCta: "Sign up",
      },
      signup: {
        loadingTitle: "Creating account",
        loadingDescription: "We are preparing your msgflash workspace and finalizing your sign-up.",
        conflict: "An account with this email already exists.",
        validationError: "Check your information and try again.",
        genericError: "Sign-up failed. Please try again.",
        resendVerificationFailed: "Unable to resend verification email right now.",
        verifyTitle: "Verify your email",
        verifyDescriptionPrefix:
          "Your account has been created. A verification link was sent to",
        verifyStepOpenInbox: "Open your inbox and click the link to activate your account.",
        verifyStepSpam: "Also check your spam folder if you do not see the email right away.",
        resending: "Resending...",
        resendVerification: "Resend verification email",
        backToLogin: "Back to login",
        openGmail: "Open Gmail",
        title: "Create an account",
        subtitle: "Start sending your messages in production.",
        continueWithGoogle: "Sign up with Google",
        orEmail: "or with email",
        fullName: "Full name",
        workEmail: "Work email",
        phone: "Phone",
        password: "Password",
        termsPrefix: "I accept the",
        termsLink: "Terms of service",
        termsAnd: "and the",
        privacyLink: "Privacy policy",
        submit: "Create my account",
        submitting: "Creating...",
        hasAccount: "Already have an account?",
        loginCta: "Sign in",
        loginHint: "Sign in →",
        passwordRules: {
          min: "At least 8 characters",
          upper: "One uppercase letter",
          lower: "One lowercase letter",
          number: "One number",
          special: "One special character",
        },
      },
      resetPassword: {
        ruleInvalid: "Password does not meet required criteria.",
        mismatch: "Passwords do not match.",
        invalidPassword: "Password is invalid or too short.",
        invalidToken: "This reset link is invalid or expired.",
        unauthorized: "Unable to reset password for this account.",
        genericError: "Unable to reset password. Please try again.",
        validatingTitle: "Validating your reset link...",
        validatingDescription: "We are checking whether your link is still valid.",
        expiredTitle: "This reset link is invalid or expired.",
        expiredDescription: "Request a new link to continue.",
        requestNew: "Request a new link",
        updatingTitle: "Updating password",
        updatingDescription: "We are securely applying your new password.",
        title: "Set a new password",
        subtitle: "Choose a new password for your account.",
        successTitle: "Your password has been updated successfully.",
        successDescription: "You can now sign in with your new password.",
        newPassword: "New password",
        confirmPassword: "Confirm password",
        submit: "Reset password",
        submitting: "Updating...",
      },
      verifyEmail: {
        resendSuccess: "A new verification link has been sent.",
        resendFailed: "Unable to resend the link right now.",
        loadingTitle: "Verifying your email",
        loadingDescription: "We are validating your link and activating your account.",
        goToLogin: "Go to login",
        resend: "Resend verification email",
        resending: "Resending...",
        states: {
          successTitle: "Email verified",
          successDescription: "Your account is now active. You can sign in.",
          alreadyVerifiedTitle: "Email already verified",
          alreadyVerifiedDescription:
            "Your account is already active. You can sign in right away.",
          expiredTitle: "Link expired",
          expiredDescription: "This verification link has expired. Request a new one to continue.",
          usedTitle: "Link already used",
          usedDescription:
            "This link has already been used. If your account is not active, request a new one.",
          invalidTitle: "Invalid link",
          invalidDescription: "This verification link is not valid.",
          errorTitle: "Verification failed",
          errorDescription: "We could not verify your email right now.",
        },
      },
      callback: {
        title: "Signing in to msgflash",
        description: "We are validating your identity and opening your workspace securely.",
      },
    },
    globalSearch: {
      placeholder: "Global search…",
      shortcut: "⌘K",
      minChars: "Type at least 2 characters to start a global search.",
      scope: "Search across pages, instances, messages, campaigns, contacts and groups.",
      searching: "Searching...",
      noResults: "No results.",
      categories: {
        page: "Page",
        instance: "Instance",
        message: "Message",
        campaign: "Campaign",
        contact: "Contact",
        group: "Group",
      },
      staticPages: [
        { id: "page-dashboard", title: "Dashboard", description: "Overview of the portal", href: "/dashboard" },
        { id: "page-instances", title: "Instances", description: "Manage WhatsApp connections", href: "/instances" },
        { id: "page-messages", title: "Messages", description: "Send and review messages", href: "/messages" },
        { id: "page-campaigns", title: "Campaigns", description: "Run bulk sends", href: "/campaigns" },
        { id: "page-contacts", title: "Contacts", description: "Address book and imports", href: "/contacts" },
        { id: "page-contact-groups", title: "Contact groups", description: "Organize contacts by groups", href: "/contacts/groups" },
        { id: "page-templates", title: "Templates", description: "Message template library", href: "/templates" },
        { id: "page-webhooks", title: "Webhooks", description: "Receive portal events", href: "/webhooks" },
        { id: "page-api-keys", title: "API Keys", description: "Manage public API access", href: "/api-keys" },
        { id: "page-billing", title: "Billing", description: "Plan, quotas and payments", href: "/billing" },
        { id: "page-profile", title: "Profile", description: "Account details", href: "/profile" },
      ],
      fallbackInstanceDescription: "WhatsApp instance",
      messagePreview: "Message {{type}}",
      campaignWithStatus: "Campaign {{status}}",
    },
    apiKeys: {
      pageTitle: "API keys",
      pageDescription: "Manage your access keys for the public API.",
      docs: "API docs",
      newKey: "New API key",
      quickTitle: "Quick integration",
      quickDescription: "Send your first message in seconds",
      copy: "Copy",
      copied: "Copied",
      loadError: "Unable to load API keys.",
      emptyTitle: "No API keys yet.",
      emptyDescription: "Create your first key.",
      usageSummary: "Usage summary",
      requestsOnPeriod: "requests in",
      thisMonth: "this month",
      activeKeys: "Active keys",
      statusActive: "Active",
      statusRevoked: "Revoked",
      requests: "requests",
      monthlyTrafficShare: "of monthly traffic",
      none: "None",
      never: "Never",
      revoke: "Revoke",
      tableHeadersLoading: ["Name", "Prefix", "Requests (month)", "Last use", "Created at", "Actions"],
      tableHeaders: ["Key", "Usage this month", "Last request", "Last use", "Created at", "Actions"],
      createModal: {
        title: "New API key",
        name: "Name",
        placeholder: "e.g. Production app",
        cancel: "Cancel",
        create: "Create",
      },
      createdModal: {
        title: "API key created",
        warning: "This is the only time this key will be shown. Copy it now.",
        confirm: "I copied the key",
      },
      revokeModal: {
        title: "Revoke API key",
        promptPrefix: "Are you sure you want to revoke",
        promptSuffix: "Any application using this key will stop working immediately.",
        cancel: "Cancel",
      },
      toast: {
        notAvailableOnPlan:
          "API keys are not available on the Free plan. Upgrade your plan to access them.",
        maxReached: "You reached the API key limit. Revoke an existing key or upgrade your plan.",
        createFailed: "Unable to create API key.",
        revoked: "API key revoked",
        revokeFailed: "Unable to revoke key.",
      },
    },
    billing: {
      pageTitle: "Billing",
      pageDescription: "Manage your plan and track monthly usage.",
      loadErrorTitle: "Unable to load billing data",
      planCurrent: "Current plan",
      planStatusActive: "Active",
      planStatusTrial: "Trial",
      planStatusPastDue: "Payment overdue",
      planStatusCancelled: "Cancelled",
      planStatusExpired: "Expired",
      recurring: "per month",
      apiRequests: "API requests / month",
      messagesPerMonth: "messages / statuses per month",
      apiKey: "API key",
      apiKeys: "API keys",
      webhookEndpoint: "webhook endpoint",
      webhookEndpoints: "webhook endpoints",
      instances: "instances",
      contactGroupsSuffix: "contact groups",
      contactGroupsUnlimited: "Unlimited contact groups",
      planActuel: "Current plan",
      currentPlan: "Current plan",
      availablePlans: "Available plans",
      features: {
        campaigns: "Campaigns",
        statuses: "WhatsApp statuses",
        webhooks: "Webhooks",
        voiceNotes: "Voice notes",
      },
      priceUnit: "€ / month",
      yes: "yes",
      no: "no",
      unlimited: "Unlimited",
      percentUsed: "used",
      currentBadge: "Current",
      scheduledBadge: "Scheduled",
      currentPlanButton: "Current plan",
      downgrade: "Downgrade",
      updatePayment: "Update",
      choosePlan: "Choose a plan",
      cancelScheduledChange: "Cancel this change",
      cancelTermination: "Cancel termination",
      cancelChange: "Cancel change",
      changePlan: "Change plan",
      usageTitle: "Usage",
      messages: "Messages",
      statuses: "Statuses",
      paymentHistory: "Payment history",
      loadingPayments: "Loading…",
      noPayments: "No payments recorded yet",
      paymentTableHeaders: ["Date", "Plan", "Period", "Amount", "Status"],
      paymentStatusSucceeded: "Succeeded",
      paymentStatusFailed: "Failed",
      paymentStatusRefunded: "Refunded",
      paymentStatusPending: "Pending",
      pageOf: "Page",
      of: "of",
      cancelSubscriptionTitle: "Cancel subscription",
      cancelSubscriptionCta: "Cancel subscription",
      cancelSubscriptionKeepAccessPrefix: "You will keep access",
      cancelSubscriptionUntilPrefix: "until",
      cancelSubscriptionUntilFallback: "the end of your current period",
      cancelSubscriptionThenFree: "then switch to the Free plan.",
      scheduledDowngradeNoticePrefix: "Your plan will change from",
      scheduledDowngradeNoticeOn: "on",
      scheduledCancelNoticePrefix: "Your subscription will end on",
      scheduledCancelNoticeSuffix: "You will switch to the Free plan.",
      cancelScheduledBadge: "Cancellation scheduled",
      downgradeScheduledBadgePrefix: "Downgrade →",
      expiresOn: "Expires on",
      renewsOn: "Renewal:",
      modals: {
        changePlanTitle: "Change plan",
        changePlanDescription: "Choose the plan that fits your needs.",
        noPlans: "Unable to load plans. Please try again.",
        cancelTitle: "Cancel subscription",
        cancelDescription: "This action will schedule cancellation at period end.",
        keepPlan: "Keep plan",
        confirmCancel: "Confirm cancellation",
        cancelScheduledTitle: "Cancel planned change",
        cancelTerminationTitle: "Cancel termination",
        back: "Back",
        confirm: "Confirm",
        scheduledDowngradeUpgradeHintPrefix: "Downgrade to",
        scheduledDowngradeUpgradeHintSuffix:
          "scheduled. An upgrade will automatically cancel this change.",
        scheduledCancelUpgradeHint:
          "Cancellation scheduled. An upgrade will automatically cancel it.",
        cancelPeriodTextPrefix: "Your subscription will be canceled at the end of the current period",
        cancelPeriodTextSuffix:
          "You will keep access until that date, then automatically move to the free plan.",
        scheduledCancelKeepPlanPrefix: "Your subscription will remain active on",
        scheduledDowngradeCancelPrefix: "Downgrade to",
        scheduledDowngradeCancelSuffix: "will be canceled. Your plan",
        scheduledDowngradeCancelSuffix2: "will remain active.",
        currentPlanFallback: "current",
        scheduledChangeCancelled: "This scheduled change will be canceled.",
      },
      alerts: {
        pastDueTitle: "Payment overdue",
        pastDueDescription:
          "Your last payment failed. Update your payment method to keep access to your plan.",
        expiredTitle: "Subscription expired",
        expiredDescription: "Your subscription expired. Choose a plan to keep using the platform.",
      },
      toast: {
        paymentReceived: "Payment received! Updating your plan...",
        planUpdated: "Your plan has been updated.",
        paymentCancelled: "Payment canceled. Your plan did not change.",
        downgradeScheduledPrefix: "Downgrade to",
        downgradeScheduledSuffix: "scheduled at period end.",
        changeAlreadyScheduled: "A plan change is already scheduled.",
        invalidPlanChange: "This plan change is not possible. Use cancellation to switch to the free plan.",
        noActiveSubscription: "No active subscription.",
        planUnavailable: "This plan is not available.",
        paymentTemporarilyUnavailable: "Payment is temporarily unavailable. Try again later.",
        changeFailed: "Unable to change plan. Please try again.",
        cancelSuccessPrefix: "Subscription canceled — access",
        cancelSuccessSuffix: "kept until period end.",
        alreadyOnFree: "You are already on the free plan.",
        cancelFailed: "Unable to cancel subscription. Please try again.",
        scheduledCancelled: "Scheduled change has been canceled.",
        noScheduledChange: "No scheduled change to cancel.",
        scheduledCancelFailed: "Unable to cancel scheduled change. Please try again.",
      },
    },
    templates: {
      pageTitle: "Templates",
      pageDescription: "Reusable message template library.",
      newTemplate: "New template",
      emptyTitle: "No templates yet",
      emptyDescription: "Create your first text or media template.",
      editTitle: "Edit template",
      deleteTitle: "Delete template",
      deleteConfirm: "Delete",
      edit: "Edit",
      preview: "Preview",
      delete: "Delete",
      confirmDelete: "Delete",
      previous: "Previous",
      next: "Next",
      modifiedAt: "Updated on",
      media: "Media",
      bodyOptional: "Body (optional)",
      body: "Body",
      name: "Name",
      type: "Type",
      templateUpdated: "Template updated",
      templateDeleted: "Template deleted",
      templateUpdateFailed: "Unable to save the template.",
      templateDeleteFailed: "Unable to delete the template.",
      invalidTemplate: "This template contains invalid placeholders or an incomplete media setup.",
      validationError: "Check the required template fields.",
      new: {
        title: "New template",
        description: "Create a reusable message with dynamic variables.",
        back: "Back to templates",
        variableSyntax: "Variable syntax",
        variableSyntaxDescription:
          "Use {{path.to.value}} to insert dynamic variables. They will be replaced automatically when sending.",
        customVariables: "Custom variables",
        customVariablesDescription:
          "Defined by you at send time or in campaigns. Ex: {{custom.code}}, {{custom.amount}}",
        examplesTitle: "Template examples",
        hide: "Hide",
        show: "Show",
        copied: "Copied",
        copy: "Copy",
        infoTitle: "Information",
        templateName: "Template name",
        mediaUrl: "Media URL",
        bodyTitle: "Message body",
        bodyDescription:
          "Write your message using {{...}} variables. Click variables above to insert them.",
        bodyPlaceholder: "Hello {{contact.firstName}}, use {{custom.code}} today.",
        variablesDetected: "Detected variables",
        autoResolved: "Auto-resolved",
        toProvideOnSend: "Provide at send time",
        noVariablesDetected:
          "No variable detected. Use {{contact.firstName}} for example.",
        submitHint: "Fill name and message body to create the template.",
        cancel: "Cancel",
        create: "Create template",
        created: "Template created",
        saveFailed: "Unable to save template.",
        invalid: "This template has invalid placeholders or incomplete media setup.",
        requiredFields: "Check required template fields.",
        autoVariables: {
          contact: "Contact data",
          user: "Your user data",
          instance: "Instance data",
        },
        examples: {
          followup: "Personalized follow-up",
          order: "Order confirmation",
          notice: "Service notice",
        },
      },
    },
    contacts: {
      pageTitle: "Contacts",
      pageDescription: "Address book, CSV imports and contact groups.",
      newContact: "New contact",
      addContact: "Add contact",
      editContact: "Edit contact",
      deleteContact: "Delete contact",
      saveContact: "Save",
      emptyTitle: "No contacts yet",
      emptyDescription: "Add your first contact or import a CSV.",
      importContacts: "Import CSV contacts",
      importStepUpload: "Choose file",
      importStepPreview: "Preview",
      importStepResult: "Result",
      contactAdded: "Contact added",
      contactUpdated: "Contact updated",
      contactDeleted: "Contact deleted",
      importSuccess: "Contacts imported successfully",
      importPartial: "Partial import: some contacts were skipped.",
      importFailed: "Unable to import the file.",
      sampleFile: "Download a CSV sample",
      fileTooLarge: "The file exceeds 5MB.",
      csvInvalid: "Invalid CSV file. Check headers and encoding.",
      csvTooLarge: "File too large. Max 5MB and 10,000 rows.",
      conflict: "A contact with this number already exists.",
      phone: "Phone",
      tags: "Tags (optional)",
      tagsHint: "Separated by commas",
      importContactsButton: "Import",
      importBack: "Back",
      importChooseFile: "Choose file",
      importPreview: "Preview",
      importResult: "Result",
      importCancelled: "Import cancelled",
      contactTablePhone: "Phone",
      contactTableName: "Name",
      contactTableTags: "Tags",
      contactTableGroups: "Groups",
      contactTableCreatedAt: "Created at",
      noContactFound: "No contacts found.",
      groups: {
        pageTitle: "Contact groups",
        back: "Back",
        newGroup: "New group",
        emptyTitle: "No groups yet.",
        emptyDescription: "Create your first group to organize contacts.",
        created: "Group created",
        updated: "Group updated",
        deleted: "Group deleted",
        notFound: "Group not found.",
        saveFailed: "Unable to save group.",
        updateFailed: "Unable to update group.",
        deleteFailed: "Unable to delete group.",
        maxReached: "Group limit reached. Upgrade your plan.",
        nameConflictPrefix: "A group named",
        view: "View",
        edit: "Edit",
        delete: "Delete",
        remove: "Remove",
        save: "Save",
        cancel: "Cancel",
        loadMore: "Load more",
        export: "Export",
        exporting: "Export in progress...",
        exportFailed: "Unable to export group.",
        addContacts: "Add contacts",
        removeMemberFailed: "Unable to remove contact.",
        removeMemberSuccess: "Contact removed from group",
        addMembersFailed: "Unable to add contacts.",
        addMembersTitle: "Add contacts to group",
        searchMembersPlaceholder: "Search members...",
        searchContactsPlaceholder: "Search by name or number...",
        loading: "Loading...",
        noContactsAvailable: "No contacts available.",
        noMembers: "No contacts in this group.",
        noMembersDescription: "Add contacts to get started.",
        createModalTitle: "New group",
        editModalTitle: "Edit group",
        deleteModalTitle: "Delete group",
        removeModalTitle: "Remove from group",
        name: "Name",
        description: "Description (optional)",
        descriptionPlaceholder: "Group description...",
        color: "Color",
        customColorTitle: "Custom color",
        detailsCountSuffix: "contact",
        detailsCountSuffixPlural: "contacts",
        createdAt: "Added on",
        table: {
          name: "Name",
          phone: "Phone",
          tags: "Tags",
          addedAt: "Added on",
        },
      },
    },
    numberLookups: {
      pageTitle: "Number Lookups",
      pageDescription: "Check a number's validity and import recognized contacts.",
      importContacts: "Import into a group",
      contactsImported: "Contacts imported successfully",
      partialImport: "Some contacts were imported, others were skipped.",
      lookupStarted: "Lookup started. Results will be available shortly.",
      lookupCompleted: "Lookup completed",
      lookupFailed: "Lookup failed. Please try again.",
      processing: "Lookup in progress... Results will be available in a few moments.",
      history: "History",
      emDash: "—",
      detail: {
        title: "Lookup details",
        instance: "Instance",
        instanceStatus: "Instance status",
        requested: "Requested",
        onWhatsApp: "WhatsApp",
        absent: "Not on WhatsApp",
        invalid: "Invalid",
        invalidNumbers: "Invalid numbers",
        notOnWhatsApp: "Not on WhatsApp",
        onWhatsAppTitle: "On WhatsApp",
        normalized: "Normalized:",
        progress: "Progress",
        completedOn: "Completed on {{date}}",
        importOne: "Import {{count}} contact",
        importMany: "Import {{count}} contacts",
        alreadyImported: "Contacts already imported",
        close: "Close",
        status: {
          done: "Completed",
          failed: "Failed",
          pending: "Pending",
          processing: "In progress",
        },
      },
      historyTable: {
        empty: "No lookups yet.",
        headers: ["Date", "Instance", "Status", "Requested", "WhatsApp", "Absent", "Invalid", "Actions"],
        viewDetails: "View details",
        importContacts: "Import contacts",
        imported: "Imported",
        mobileWhatsApp: "WhatsApp:",
        mobileAbsent: "Absent:",
        mobileInvalid: "Invalid:",
      },
      resultsTabs: {
        onWhatsApp: "On WhatsApp",
        notOnWhatsApp: "Absent",
        invalid: "Invalid",
        emptyCategory: "No results in this category.",
        normalized: "Normalized:",
        reasonPrefix: "Reason:",
      },
    },
    dashboard: {
      pageTitle: "Dashboard",
      pageDescription: "Overview of your WhatsApp activity",
      noInstance: "No connected WhatsApp instance.",
      connectNow: "Connect now →",
      messagesThisMonth: "Messages this month",
      activeInstances: "Active instances",
      apiRequestsThisMonth: "API requests this month",
      campaignsRunning: "Running campaigns",
      active: "Active",
      noSends: "No sends",
      online: "Online",
      offline: "Offline",
      thisMonth: "This month",
      total: "total",
      usagePlan: "Usage — Plan",
      quotaExhausted: "Quota exhausted",
      quotaNear: "Quota almost exhausted",
      messagesStatuses: "Messages & Statuses",
      apiRequests: "API requests",
      quotaResetOn: "Quota resets on",
      recentMessages: "Recent messages",
      recentCampaigns: "Recent campaigns",
      seeAll: "See all →",
      noMessages: "No messages sent yet.",
      sendFirstMessage: "Send your first message",
      noCampaigns: "No campaigns yet.",
      createCampaign: "Create a campaign",
      quickActions: "Quick actions",
      sendMessage: "Send message",
      newCampaign: "New campaign",
      connectWhatsapp: "Connect WhatsApp",
      generateApiKey: "Generate API key",
      status: {
        queued: "Queued",
        sent: "Sent",
        delivered: "Delivered",
        read: "Read",
        failed: "Failed",
        draft: "Draft",
        scheduled: "Scheduled",
        running: "Running",
        paused: "Paused",
        pausedQuota: "Paused (quota)",
        pausedPlan: "Paused (plan)",
        completed: "Completed",
      },
    },
    messages: {
      title: "New Message",
      description: "Send now or schedule a message with upload tracking and action status.",
      sendBack: "Back to messages",
      draft: "Freeform",
      template: "Use template",
      instance: "Instance",
      selectInstance: "Select an instance...",
      noInstance: "No connected instance available.",
      selectTemplate: "Select a template...",
      variables: "Template variables",
      uploadSuccess: "File uploaded successfully.",
      uploadQueued: "Media ready. You can review and send it.",
      uploadInProgress: "Uploading media...",
      mediaRemoved: "Media removed. You can choose another one.",
      typeUpdated: "Message type updated.",
      queuedSuccess: "Message queued successfully.",
      scheduledSuccess: "Message scheduled successfully.",
      sending: "Sending message...",
      scheduling: "Scheduling message...",
      queuedNote: "The message was queued for delivery.",
      templatePreview: "Template preview updated.",
      templatePreviewLoading: "Generating template preview...",
      templatePreviewError: "Unable to generate the template preview.",
      recipient: {
        title: "Recipient",
        manual: "New number",
        contact: "Saved contact",
        chooseContact: "Choose a contact",
        selectContact: "Select a contact...",
        phoneLabel: "Recipient (number)",
        noContact:
          "No saved contact available. Add one or use a new number.",
      },
      voiceRecorder: {
        title: "Voice note",
        description: "Record your voice, review it, then upload it before final send.",
        browserUnsupported: "Voice recording is not supported on this browser.",
        mimeUnsupported:
          "Your browser does not support a compatible audio format for voice notes. Use audio file upload instead.",
        micDisconnected: "Microphone connection lost. Recording canceled.",
        silenceDetected: "No voice detected. Check your microphone volume.",
        micDenied:
          "Microphone access denied. Please allow microphone access in your browser settings.",
        micNotFound: "No microphone detected. Connect a device to continue.",
        micBusy: "The microphone is already used by another app.",
        startFailed: "Unable to start voice recording.",
        startRecording: "Start recording",
        micRequestedOnClick: "Microphone permission is requested only on click.",
        recording: "Recording in progress...",
        cancel: "Cancel",
        stop: "Stop",
        remove: "Delete",
        rerecord: "Record again",
        uploadVoiceNote: "Upload voice note",
      },
      detail: {
        notFound: "Message not found.",
        backToMessages: "Back to messages",
        title: "Message details",
        back: "Back",
        template: "Template",
        sendFailed: "Send failed",
        status: "Status",
        type: "Type",
        recipient: "Recipient",
        instance: "Instance",
        providerId: "Provider ID",
        content: "Content",
        createdAt: "Created at",
        updatedAt: "Updated at",
        campaign: "Campaign",
        viewCampaign: "View campaign →",
        contact: "Contact",
        templateRender: "Template render",
        templateId: "Template ID",
        usedVariables: "Used variables",
        missingVariables: "Missing variables",
        renderCode: "Render code",
        none: "None",
        types: {
          text: "Text",
          image: "Image",
          video: "Video",
          audio: "Audio",
          voice_note: "Voice note",
          document: "Document",
        },
      },
      mediaUpload: {
        uploading: "Upload in progress...",
        uploadingHint: "The file is being sent to secure temporary storage.",
        fileDetails: "{{size}} · {{mime}} · expires {{date}}",
        replace: "Replace",
        tempHostNotice: "The file is hosted temporarily and deleted automatically after expiry.",
        publicLinkNotice: "The generated link is public. Do not upload sensitive documents.",
        scheduleExpiryWarning: "If the scheduled time is after expiry, sending may fail.",
        chooseFile: "Choose file",
        acceptedMax: "{{accepted}} · max {{size}}",
        mediaFieldLabel: {
          image: "Image",
          video: "Video",
          document: "Document",
          audio: "Audio file",
          voice_note: "Voice note",
        },
      },
      buttonBuilder: {
        title: "Buttons",
        add: "Add",
        emptyHint: "No buttons configured. Add up to 2 interactive buttons.",
        buttonN: "Button {{n}}",
        typeLabel: "Button type",
        displayText: "Display text",
        displayPlaceholder: "e.g. Visit site",
        buttonId: "Button ID",
        buttonIdHint: "Unique identifier for the callback",
        copyCode: "Text to copy",
        copyPlaceholder: "e.g. PROMO2024",
        url: "URL",
        phone: "Phone number",
        pixCurrency: "Currency",
        pixRecipientName: "Recipient name",
        pixKeyType: "Pix key type",
        pixKeyTypePlaceholder: "Select...",
        pixKey: "Pix key",
        pixKeyPlaceholder: "e.g. 123.456.789-00",
        pixCompanyPlaceholder: "Acme Inc.",
        types: {
          reply: "Reply",
          copy: "Copy",
          url: "Link",
          call: "Call",
          pix: "Pix",
        },
        pixKeyTypes: {
          cpf: "CPF",
          cnpj: "CNPJ",
          email: "Email",
          phone: "Phone",
          random: "Random",
        },
      },
      sendStatus: {
        progressLabel: "Progress",
        title: "Send tracking",
        mediaUpload: "Media upload",
        actionStatus: "Action status",
        mediaExpiryNote: "Temporary media must stay valid until the message is actually sent.",
      },
    },
    instances: {
      health: {
        title: "Warmup & health",
        loadError: "Unable to load warmup data.",
        retry: "Retry",
        firstConnected: "First connected:",
        hourlyCap: "Hourly cap",
        dailyCap: "Daily cap",
        maxCampaign: "Max campaign",
        maxColdRatio: "Max cold-contact ratio",
        activityTitle: "Recent activity",
        window1h: "1h",
        window24h: "24h",
        sentUnique: "{{sent}} sent · {{unique}} recip.",
        replies: "Replies",
        repliesLine: "{{in24}} (24h) · {{in7}} (7d)",
        recommendations: "Recommendations",
        states: {
          new: "New",
          warming: "Warming up",
          stable: "Stable",
          at_risk: "At risk",
          restricted: "Restricted",
        },
      },
    },
    campaigns: {
      title: "New Campaign",
      description: "Configure and schedule a bulk send to your contacts.",
      back: "Back to campaigns",
      general: "General information",
      recipients: "Recipients",
      contentTemplate: "Template",
      contentDirect: "Freeform",
      create: "Create campaign",
      created: "Campaign created successfully.",
      createdWarmup: "Campaign created with warmup guidance",
      paused: "Campaign paused",
      resumed: "Campaign resumed",
      resumedWarmup: "Campaign resumed with warmup guidance",
      cancelled: "Campaign cancelled",
      deleted: "Campaign deleted",
      planed: "Campaign scheduled",
      safety: {
        title: "Warmup guidance",
        riskPrefix: "Risk level:",
        riskLow: "Low",
        riskMedium: "Medium",
        riskHigh: "High",
        scorePrefix: "Score:",
        reasons: "Reasons",
        recommendations: "Recommendations",
        maxCampaignRecipients: "Max campaign recipients",
        maxColdRatio: "Max cold-contact ratio",
        audienceTitle: "Audience ({{count}} recipients)",
        warmContacts: "Warm contacts",
        coldContacts: "Cold contacts",
        unknownContacts: "Unknown",
      },
    },
    webhooks: {
      newTitle: "New webhook",
      newDescription: "Add an endpoint to receive real-time event notifications.",
      back: "Back to webhooks",
      endpointTitle: "Endpoint URL",
      endpointDescription: "The URL that will receive POST notifications.",
      endpointLabel: "Webhook URL",
      eventsTitle: "Events",
      eventsDescription: "Select events to receive.",
      minEvent: "Select at least one event.",
      hmacNotice: "The HMAC-SHA256 signing key will be shown only once after creation.",
      cancel: "Cancel",
      create: "Create webhook",
      createdTitle: "Webhook created",
      secretWarning: "Copy this signing key. It will never be shown again.",
      secretLabel: "HMAC-SHA256 signing key",
      endpointLabelShort: "Endpoint",
      close: "Close",
      viewWebhooks: "View webhooks",
      planBlocked:
        "Webhooks are not available on the Free plan. Upgrade to the Starter plan to access them.",
      errors: {
        planUnavailable: "Webhooks are not available on your plan.",
        limitReached: "Webhook endpoint limit reached for your plan.",
        saveFailed: "Unable to save endpoint.",
      },
      events: {
        messageSent: "Message sent",
        messageDelivered: "Message delivered",
        messageFailed: "Message failed",
        instanceConnected: "Instance connected",
      },
    },
    toasts: {
      lookupCompleted: "Lookup completed",
      lookupFailed: "Lookup failed. Please try again.",
      lookupStarted: "Lookup started. Results will be available shortly.",
      contactsImported: "Contacts imported successfully",
      partialImport: "Some contacts were imported, others were skipped.",
      instanceCreated: "Instance created",
      instanceConnected: "WhatsApp connected!",
      instanceDisconnected: "WhatsApp disconnected",
      profileUpdated: "Profile updated",
    },
  },
} satisfies Record<PortalLocale, Record<string, unknown>>
